set nocompatible    " required for Vundle
filetype off        " required for Vundle

" Vundle init
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'   " required, let Vundle manage itself

" Plugin list
Plugin 'itchyny/lightline.vim'
Plugin 'raimondi/delimitmate'
Plugin 'scrooloose/syntastic'
Plugin 'airblade/vim-gitgutter'
Plugin 'valloric/youcompleteme'
Plugin 'ctrlpvim/ctrlp.vim'

call vundle#end()

" Global setup after this -------------------
filetype plugin indent on
syntax on
colorscheme Tomorrow-Night

" Tabs settings
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
autocmd Filetype html setlocal ts=2 sw=2
autocmd Filetype css setlocal ts=2 sw=2
autocmd Filetype ruby setlocal ts=2 sw=2
autocmd Filetype scala setlocal ts=2 sw=2

" Line numbers on
set number

" Width
set nowrap
set textwidth=80

" Quick ESC in insert mode
imap jj <ESC>
" Jump to the next row
map <Down> gj
map <Up> gk
nnoremap j gj
nnoremap k gk
" Easy tab navigation
nnoremap ;; :tabn<CR>
nnoremap ,, :tabp<CR>
" Open new splits to right and bottom
set splitbelow
set splitright
" Easy split navigation
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
" Quick split swap
nnoremap <tab><tab> <C-W>R
" Break out current window into a new tab
nnoremap ;n <C-W>T

" Search behavior
set incsearch
set ignorecase
set smartcase
set hlsearch
nmap <C-U> :nohlsearch<CR>

" Status line
" set statusline=%f\ %y%=\ Line:\ %l/%L\ Col:\ %c
set laststatus=2
let g:lightline = {
    \ 'colorscheme': 'Tomorrow_Night',
    \ }

" Enable mouse in all (a) modes
set mouse=a

" Delimitmate
let delimitMate_expand_cr = 1
let delimitMate_expand_space = 1
" Syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_loc_list_height = 5
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0
let g:syntastic_enable_highlighting = 0
let g:syntastic_error_symbol = '!'
let g:syntastic_style_error_symbol = '?'
let g:syntastic_warning_symbol = '>'
let g:syntastic_style_warning_symbol = '~'

" Optional local setup
try
    source ~/.vimrc-local
catch
    " No local setup : ignore.
endtry

