set nocompatible    " required for Vundle
filetype off        " required for Vundle

" Vundle init
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'   " required, let Vundle manage itself

" Plugin list
Plugin 'itchyny/lightline.vim'
" Plugin 'scrooloose/nerdtree'
Plugin 'raimondi/delimitmate'
Plugin 'airblade/vim-gitgutter'
Plugin 'valloric/youcompleteme'
Plugin 'ctrlpvim/ctrlp.vim'

call vundle#end()

" Global setup after this -------------------
filetype plugin indent on
syntax on
colorscheme Tomorrow-Night

" Tabs behavior
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

" Line numbers on
set number

" Width
set nowrap
set textwidth=80

" Quick ESC in insert mode
imap jj <ESC>
" Jump to the next row
map <Down> gj
map <Up> gk
nnoremap j gj
nnoremap k gk
" Easy tab navigation
nnoremap ;; :tabn<CR>
nnoremap ,, :tabp<CR>
" Open new splits to right and bottom
set splitbelow
set splitright
" Easy split navigation
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
" Quick split swap
nnoremap <tab><tab> <C-W>R
" Break out current window into a new tab
nnoremap ;n <C-W>T

" Search behavior
set incsearch
set ignorecase
set smartcase
set hlsearch
nmap <C-U> :nohlsearch<CR>

" Status line
" set statusline=%f\ %y%=\ Line:\ %l/%L\ Col:\ %c
set laststatus=2
let g:lightline = {
    \ 'colorscheme': 'Tomorrow_Night',
    \ }

" NERDTree mapping
noremap <C-N> :<C-U>NERDTreeToggle<CR>

" Optional local setup
try
    source ~/.vimrc-local
catch
    " No local setup : ignore.
endtry

